name: Build & Push Spring PetClinic Image
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4    
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn clean package -DskipTests


      # -----------------------------------------------------
      # Install & Configure JFrog CLI for Build + Xray Scan
      # -----------------------------------------------------
      - name: Install JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4

      - name: Configure JFrog CLI
        run: |
          jf config add myserver \
            --url="${{ secrets.JF_URL }}" \
            --user="${{ secrets.JF_USERNAME }}" \
            --password="${{ secrets.JF_PASSWORD }}" \
            --interactive=false

      # -----------------------------------------------------
      # XRAY SCAN â€” FAIL IF VULNS FOUND
      # -----------------------------------------------------
      - name: Xray Security Scan
        run: |
          jf rt build-scan petclinic-build ${{ github.run_number }} \
            --vuln \
            --fail-on-severity High
      # If you don't want to fail pipeline, remove:
      #      --fail-on-severity High

      - name: Login to Docker registry (Artifactory)
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.ARTIFACTORY_REGISTRY }}/petclinic/spring-petclinic:latest
            ${{ secrets.ARTIFACTORY_REGISTRY }}/petclinic/spring-petclinic:${{ github.sha }}

      # 6. Display done
      - name: Show image pushed message
        run: echo "Docker image for Spring PetClinic pushed to registry"
